# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfctl < Formula
  desc "CLI to query Terraform/OpenTofu state across backends"
  homepage "https://github.com/tfctl/tfctl"
  version "1.2.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tfctl/homebrew-tfctl/releases/download/v1.2.3/tfctl_1.2.3_darwin_x86_64.tar.gz"
      sha256 "009b74d416ee7d4894759fd7c9a480dc14737a9fa317ff9a1096c9578afabf2b"

      define_method(:install) do
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tfctl/homebrew-tfctl/releases/download/v1.2.3/tfctl_1.2.3_darwin_arm64.tar.gz"
      sha256 "e7b073332169e3415031c032d7187e8cbb3685cbdaf00517007eddf569afb3cf"

      define_method(:install) do
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tfctl/homebrew-tfctl/releases/download/v1.2.3/tfctl_1.2.3_linux_x86_64.tar.gz"
      sha256 "1660ad3930feabcc0af3d058af8a16c54f604e672c4e332574db3a7578c71f03"
      define_method(:install) do
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tfctl/homebrew-tfctl/releases/download/v1.2.3/tfctl_1.2.3_linux_arm64.tar.gz"
      sha256 "1c0180782d3b9c06d7a6a202a5f6bab9bd5e0b58d37669266006c65471c93612"
      define_method(:install) do
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
  end

  test do
    system "#{bin}/tfctl", "--version"
  end
end
