# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfquery < Formula
  desc "CLI to query Terraform/OpenTofu state across backends"
  homepage "https://github.com/tfquery/tfquery"
  version "2.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tfquery/homebrew-tfquery/releases/download/v2.0.0/tfquery_2.0.0_darwin_x86_64.tar.gz"
      sha256 "1ab8fe8e345d771b20660d7b2b7e0a8c27b4bce894022c461ef5f804b4266d87"

      define_method(:install) do
        bin.install "tfquery"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tfquery/homebrew-tfquery/releases/download/v2.0.0/tfquery_2.0.0_darwin_arm64.tar.gz"
      sha256 "fa43a8c7d26d8e37392b243aa3dd44e33f5af0983f9ae22dc71c879f6673ecc3"

      define_method(:install) do
        bin.install "tfquery"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tfquery/homebrew-tfquery/releases/download/v2.0.0/tfquery_2.0.0_linux_x86_64.tar.gz"
      sha256 "9c491ce5be96fd203ebe60b96530c69b4767c2dafccba374b18f8f8a6c70280a"
      define_method(:install) do
        bin.install "tfquery"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tfquery/homebrew-tfquery/releases/download/v2.0.0/tfquery_2.0.0_linux_arm64.tar.gz"
      sha256 "b1fc1caae168762dc38bce79ef8771dcfa89ab3816335e051a29fb478e7afe4b"
      define_method(:install) do
        bin.install "tfquery"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
  end

  test do
    system "#{bin}/tfquery", "--version"
  end
end
