# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfquery < Formula
  desc "CLI to query Terraform/OpenTofu state across backends"
  homepage "https://github.com/tfquery/tfquery"
  version "2.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tfquery/homebrew-tfquery/releases/download/v2.0.0/tfquery_2.0.0_darwin_x86_64.tar.gz"
      sha256 "6e02d4cedf32cfd806759984a332c20e7360edd12ba00e76b68d240f5e359539"

      define_method(:install) do
        bin.install "tfquery"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tfquery/homebrew-tfquery/releases/download/v2.0.0/tfquery_2.0.0_darwin_arm64.tar.gz"
      sha256 "6ea4088f4ee3e87820fddf2e1c3838b4403c7f6e89f7f8f713fd068bc949e6d5"

      define_method(:install) do
        bin.install "tfquery"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tfquery/homebrew-tfquery/releases/download/v2.0.0/tfquery_2.0.0_linux_x86_64.tar.gz"
      sha256 "c594fecfcf7b91e505d868671cf8ae03c37bc417c0f28e57892d991fbdf36373"
      define_method(:install) do
        bin.install "tfquery"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tfquery/homebrew-tfquery/releases/download/v2.0.0/tfquery_2.0.0_linux_arm64.tar.gz"
      sha256 "e671ccaa2921639262b1425aec9d13111d54afaf5aaed8f2e5e1933271f16266"
      define_method(:install) do
        bin.install "tfquery"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
      end
    end
  end

  test do
    system "#{bin}/tfquery", "--version"
  end
end
